// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFQpEYZ4wKjcDo77m5YIEr76NbcLSBogI',
    appId: '1:848892713466:web:ec80006730c695d5ca6c43',
    messagingSenderId: '848892713466',
    projectId: 'fir-test-87f76',
    authDomain: 'fir-test-87f76.firebaseapp.com',
    databaseURL: 'https://fir-test-87f76-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-87f76.firebasestorage.app',
    measurementId: 'G-6ET649E4C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CxwNEUw8TF0XLCce9TJRPuiiNNaZKP0',
    appId: '1:848892713466:android:180899a0ff7009d3ca6c43',
    messagingSenderId: '848892713466',
    projectId: 'fir-test-87f76',
    databaseURL: 'https://fir-test-87f76-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-87f76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0UNfRohF9KQp7_hu-VsLTnZZnqJ1q7M0',
    appId: '1:848892713466:ios:e10065c477acd17eca6c43',
    messagingSenderId: '848892713466',
    projectId: 'fir-test-87f76',
    databaseURL: 'https://fir-test-87f76-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-87f76.firebasestorage.app',
    androidClientId: '848892713466-hi9ke46mejpbhanj1fah6isk2nqojb5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tictactoeonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0UNfRohF9KQp7_hu-VsLTnZZnqJ1q7M0',
    appId: '1:848892713466:ios:e10065c477acd17eca6c43',
    messagingSenderId: '848892713466',
    projectId: 'fir-test-87f76',
    databaseURL: 'https://fir-test-87f76-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-87f76.firebasestorage.app',
    androidClientId: '848892713466-hi9ke46mejpbhanj1fah6isk2nqojb5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tictactoeonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFQpEYZ4wKjcDo77m5YIEr76NbcLSBogI',
    appId: '1:848892713466:web:26d12cf77b17c6a7ca6c43',
    messagingSenderId: '848892713466',
    projectId: 'fir-test-87f76',
    authDomain: 'fir-test-87f76.firebaseapp.com',
    databaseURL: 'https://fir-test-87f76-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-87f76.firebasestorage.app',
    measurementId: 'G-X9RH9W74BT',
  );
}
